### ISSUE TITLE
Bug in async_runtime

### ISSUE THREAD

**Issue by mortenhaahr** [INTO-CPS-Association/robosapiens-trustworthiness-checker#1] opened 2024-10-10 09:12 UTC
Consider the two input files:
examples/eval.input
````
0: x = 1
   e = "x + 1"
1: x = 2
   e = "x + 2"
````
examples/eval.lola
````
in x
in e
out z
z = eval(e)
````

The expected output when running `trustworthiness_checker examples/eval.lola examples/eval.input` is:
````
Subscribed to e
Subscribed to z
s: "x + 1"
s: "x + 2"
z[0] = Int(2)
z[1] = Int(4)
````

This output occurs sometimes (it is rare). Most of the time the output is:
````
Subscribed to e
Subscribed to z
s: "x + 1"
s: "x + 2"
z[0] = Int(2)
thread 'tokio-runtime-worker' panicked at src/untimed_monitoring_combinators.rs:271:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

Note: that if we specify the queuing runtime then it always works, hence why it would make sense that the error is in the async_runtime.

**Comment by twright** [comment] 2024-10-16 11:21
Fixed by #d3eafb0

Rather than a complex concurrency bug in the runtime like we originally thought, this was just caused by an off-by-one error in a loop, causing values meant to be passed to the subcontext to be unavailable later when they are are actually needed.

**Closed by twright** 2024-10-16 11:21 UTC
